---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    yum:
      name: "*"
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

# pas mane maziau web serveriu (1), todel teoriskai Ubuntu nereikia, nauoju tik CentOS

- hosts: web_servers
  become: true
  tasks:


  - name: install apache and php for Ubuntu servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for CentOS servers
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"


# db serveris tik 1 - Ubuntu, bet cia universaliai

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"



# file serveriui naudoja package moduli, (ne youm ar apt), nes centosui ir ubuntu tas pats name of the pachage

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest
