---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (CentOS)
    tags: always
    yum:
      update_cache: yes
# cia tik counteris, kad nesiskaiciuotu playbooko pabaigoje, kad outputas butu svaresnis, cache vistie kvisada updatins, cacha updatint butina, kad playbookai nefailintu kartais
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:
  roles:
    - base
    
- hosts: workstations
  become: true
  roles:
    - workstations
 
- hosts: web_servers
  become: true
  roles:
    - web_servers
 
- hosts: db_servers
  become: true
  roles:
    - db_servers
 
- hosts: file_servers
  become: true
  roles:
    - file_servers
