  - name: install apache and php
    tags: apache,apache2,ubuntu
    package:
      name:
        - "{{ apache_package_name }}"
        - "{{ php_package_name }}"
      state: latest


  - name: start and enable apache service (CentOS tik reikia)
    tags: apache,centos,httpd
    service:
      name: "{{ apache_service }}"
      state: started
      enabled: yes

  - name: change e-mail address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin kazkada@paupdatinau.com
    when: ansible_distribution == "CentOS"
# notifikuoja play, kuris vadinamas restart_apache (handleri), kuris randasi sukurtam sukurtam web_servers subfolderyje handlers (/roles/web_servers/handlers/main.yml). Aprasytas tuo paciu pavadinimu "main.yml" faile
    notify: restart_apache



  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
